### ISSUE TITLE
Notification Icon

### ISSUE THREAD

**Issue by jrhardman64** [devotoare/google-messages-launcher#7]
I currently pin this window to my taskbar in Windows 10.  When a new message comes in, there is no notification icon that shows up to let me know that I have a new message.  There also isn't an icon up on the chrome extension icon either.  Would it be possible to add this feature?

**Comment by devotoare** [comment]
I'll look into it. It will sort of depend on if it's possible to do without adding more permissions, as I don't want to add too many permissions for something that is essentially just a pop up.

**Comment by sandrotosi** [comment]
YES! please, this will increase the compatibility with the hangouts extension (soon to be unsupported) -- thanks!

**Comment by sandrotosi** [comment]
on top of this, the notification icon should act as a "minimize" action.

now when closing the window it looks like the entire process is closed, and clicking again on the extension will create a new instance (also, it does not preserve the window location, which should be good to have). so having the notification icon + when closing the window having it "minimized" onto the notification icon would be perfect

**Comment by devotoare** [comment]
Unfortunately it would not be possible to do this without asking for additional permissions that I don't want from customers. Perhaps if there is enough interest without other extensions available in the future I'll take a look at what I can do.

Please also see #10
